print("digite 6 e 5")
A= input()
B= input()
print(A+B)
print(type(A))
print(type(B))
print(type(A+B))
print("digite novamente 6 e 5")
X= int(input())
Y= int(input())
print(X+Y)
print("x é:",type(X))
print(type(Y))
print(type(X+Y))

print("-----------------")
A,B,C= input().split()
A= int(A)
B= int(B)
print(A+B)

